// Enumerations used by the story creator UI for prompt-building dropdowns
const dreamData = {
  imageStyle: [
    'cinematic',
    'realistic',
    'retro',
    'anime',
    'graphic novel',
    'cartoon',
    'abstract',
    'futuristic',
    'storybook',
    'pixel',
    'black & white',
    'undefined',
  ],
  readingStyle: ['simple', 'casual', 'vivid', 'literary'],
  kidsMode: ['starter', 'explorer', 'legend'],
  tense: ['past', 'present', 'future'],
  writingStyle: ['descriptive', 'narrative', 'expository'],
  voice: ['active', 'passive'],
  tone: [
    'optimistic',
    'pessimistic',
    'sarcastic',
    'assertive',
    'aggressive',
    'passionate',
    'entertaining',
    'serious',
    'educational',
    'persuasive',
    'motivating',
    'curious',
    'humoristic',
    'surreal',
  ],
  relationship: ['friends', 'neutral', 'enemies'],
  min_max: ['min', 'standard', 'max'],
};

export default dreamData;
