// Enumerations used by the story creator UI for prompt-building dropdowns
const dreamData = {
  imageStyle: [
    'Cinematic',
    'Realistic',
    'Retro',
    'Anime',
    'Graphic Novel',
    'Cartoon',
    'Abstract',
    'Futuristic',
    'Storybook',
    'Pixel',
    'Black & White',
    'Undefined',
  ],
  readingStyle: ['simple', 'casual', 'vivid', 'literary'],
  kidsMode: ['starter', 'explorer', 'legend'],
  tense: ['past', 'present', 'future'],
  writingStyle: ['descriptive', 'narrative', 'expository'],
  voice: ['active', 'passive'],
  tone: [
    'optimistic',
    'pessimistic',
    'sarcastic',
    'assertive',
    'aggressive',
    'passionate',
    'entertaining',
    'serious',
    'educational',
    'persuasive',
    'motivating',
    'curious',
    'humoristic',
    'surreal',
  ],
  relationship: ['friends', 'neutral', 'enemies'],
  min_max: ['min', 'standard', 'max'],
};

export default dreamData;
